/**
 * ISO3 to ISO2 country code mapping + country metadata.
 * Used to join Climate TRACE (ISO3) with World Bank (ISO2) data.
 * Includes region classification for the Climate Justice Index.
 */

export interface CountryMeta {
  iso2: string;
  iso3: string;
  name: string;
  region: string;
}

// Comprehensive mapping covering all major countries tracked by Climate TRACE + World Bank
export const ISO3_TO_COUNTRY: Record<string, CountryMeta> = {
  AFG: { iso2: 'AF', iso3: 'AFG', name: 'Afghanistan', region: 'Asia' },
  ALB: { iso2: 'AL', iso3: 'ALB', name: 'Albania', region: 'Europe' },
  DZA: { iso2: 'DZ', iso3: 'DZA', name: 'Algeria', region: 'Africa' },
  AGO: { iso2: 'AO', iso3: 'AGO', name: 'Angola', region: 'Africa' },
  ARG: { iso2: 'AR', iso3: 'ARG', name: 'Argentina', region: 'Latin America' },
  ARM: { iso2: 'AM', iso3: 'ARM', name: 'Armenia', region: 'Asia' },
  AUS: { iso2: 'AU', iso3: 'AUS', name: 'Australia', region: 'Oceania' },
  AUT: { iso2: 'AT', iso3: 'AUT', name: 'Austria', region: 'Europe' },
  AZE: { iso2: 'AZ', iso3: 'AZE', name: 'Azerbaijan', region: 'Asia' },
  BHS: { iso2: 'BS', iso3: 'BHS', name: 'Bahamas', region: 'Latin America' },
  BHR: { iso2: 'BH', iso3: 'BHR', name: 'Bahrain', region: 'Middle East' },
  BGD: { iso2: 'BD', iso3: 'BGD', name: 'Bangladesh', region: 'Asia' },
  BLR: { iso2: 'BY', iso3: 'BLR', name: 'Belarus', region: 'Europe' },
  BEL: { iso2: 'BE', iso3: 'BEL', name: 'Belgium', region: 'Europe' },
  BLZ: { iso2: 'BZ', iso3: 'BLZ', name: 'Belize', region: 'Latin America' },
  BEN: { iso2: 'BJ', iso3: 'BEN', name: 'Benin', region: 'Africa' },
  BTN: { iso2: 'BT', iso3: 'BTN', name: 'Bhutan', region: 'Asia' },
  BOL: { iso2: 'BO', iso3: 'BOL', name: 'Bolivia', region: 'Latin America' },
  BIH: { iso2: 'BA', iso3: 'BIH', name: 'Bosnia and Herzegovina', region: 'Europe' },
  BWA: { iso2: 'BW', iso3: 'BWA', name: 'Botswana', region: 'Africa' },
  BRA: { iso2: 'BR', iso3: 'BRA', name: 'Brazil', region: 'Latin America' },
  BRN: { iso2: 'BN', iso3: 'BRN', name: 'Brunei', region: 'Asia' },
  BGR: { iso2: 'BG', iso3: 'BGR', name: 'Bulgaria', region: 'Europe' },
  BFA: { iso2: 'BF', iso3: 'BFA', name: 'Burkina Faso', region: 'Africa' },
  BDI: { iso2: 'BI', iso3: 'BDI', name: 'Burundi', region: 'Africa' },
  KHM: { iso2: 'KH', iso3: 'KHM', name: 'Cambodia', region: 'Asia' },
  CMR: { iso2: 'CM', iso3: 'CMR', name: 'Cameroon', region: 'Africa' },
  CAN: { iso2: 'CA', iso3: 'CAN', name: 'Canada', region: 'North America' },
  CPV: { iso2: 'CV', iso3: 'CPV', name: 'Cape Verde', region: 'Africa' },
  CAF: { iso2: 'CF', iso3: 'CAF', name: 'Central African Republic', region: 'Africa' },
  TCD: { iso2: 'TD', iso3: 'TCD', name: 'Chad', region: 'Africa' },
  CHL: { iso2: 'CL', iso3: 'CHL', name: 'Chile', region: 'Latin America' },
  CHN: { iso2: 'CN', iso3: 'CHN', name: 'China', region: 'Asia' },
  COL: { iso2: 'CO', iso3: 'COL', name: 'Colombia', region: 'Latin America' },
  COM: { iso2: 'KM', iso3: 'COM', name: 'Comoros', region: 'Africa' },
  COG: { iso2: 'CG', iso3: 'COG', name: 'Congo', region: 'Africa' },
  COD: { iso2: 'CD', iso3: 'COD', name: 'DR Congo', region: 'Africa' },
  CRI: { iso2: 'CR', iso3: 'CRI', name: 'Costa Rica', region: 'Latin America' },
  CIV: { iso2: 'CI', iso3: 'CIV', name: "Côte d'Ivoire", region: 'Africa' },
  HRV: { iso2: 'HR', iso3: 'HRV', name: 'Croatia', region: 'Europe' },
  CUB: { iso2: 'CU', iso3: 'CUB', name: 'Cuba', region: 'Latin America' },
  CYP: { iso2: 'CY', iso3: 'CYP', name: 'Cyprus', region: 'Europe' },
  CZE: { iso2: 'CZ', iso3: 'CZE', name: 'Czech Republic', region: 'Europe' },
  DNK: { iso2: 'DK', iso3: 'DNK', name: 'Denmark', region: 'Europe' },
  DJI: { iso2: 'DJ', iso3: 'DJI', name: 'Djibouti', region: 'Africa' },
  DOM: { iso2: 'DO', iso3: 'DOM', name: 'Dominican Republic', region: 'Latin America' },
  ECU: { iso2: 'EC', iso3: 'ECU', name: 'Ecuador', region: 'Latin America' },
  EGY: { iso2: 'EG', iso3: 'EGY', name: 'Egypt', region: 'Africa' },
  SLV: { iso2: 'SV', iso3: 'SLV', name: 'El Salvador', region: 'Latin America' },
  GNQ: { iso2: 'GQ', iso3: 'GNQ', name: 'Equatorial Guinea', region: 'Africa' },
  ERI: { iso2: 'ER', iso3: 'ERI', name: 'Eritrea', region: 'Africa' },
  EST: { iso2: 'EE', iso3: 'EST', name: 'Estonia', region: 'Europe' },
  SWZ: { iso2: 'SZ', iso3: 'SWZ', name: 'Eswatini', region: 'Africa' },
  ETH: { iso2: 'ET', iso3: 'ETH', name: 'Ethiopia', region: 'Africa' },
  FJI: { iso2: 'FJ', iso3: 'FJI', name: 'Fiji', region: 'Oceania' },
  FIN: { iso2: 'FI', iso3: 'FIN', name: 'Finland', region: 'Europe' },
  FRA: { iso2: 'FR', iso3: 'FRA', name: 'France', region: 'Europe' },
  GAB: { iso2: 'GA', iso3: 'GAB', name: 'Gabon', region: 'Africa' },
  GMB: { iso2: 'GM', iso3: 'GMB', name: 'Gambia', region: 'Africa' },
  GEO: { iso2: 'GE', iso3: 'GEO', name: 'Georgia', region: 'Asia' },
  DEU: { iso2: 'DE', iso3: 'DEU', name: 'Germany', region: 'Europe' },
  GHA: { iso2: 'GH', iso3: 'GHA', name: 'Ghana', region: 'Africa' },
  GRC: { iso2: 'GR', iso3: 'GRC', name: 'Greece', region: 'Europe' },
  GTM: { iso2: 'GT', iso3: 'GTM', name: 'Guatemala', region: 'Latin America' },
  GIN: { iso2: 'GN', iso3: 'GIN', name: 'Guinea', region: 'Africa' },
  GNB: { iso2: 'GW', iso3: 'GNB', name: 'Guinea-Bissau', region: 'Africa' },
  GUY: { iso2: 'GY', iso3: 'GUY', name: 'Guyana', region: 'Latin America' },
  HTI: { iso2: 'HT', iso3: 'HTI', name: 'Haiti', region: 'Latin America' },
  HND: { iso2: 'HN', iso3: 'HND', name: 'Honduras', region: 'Latin America' },
  HUN: { iso2: 'HU', iso3: 'HUN', name: 'Hungary', region: 'Europe' },
  ISL: { iso2: 'IS', iso3: 'ISL', name: 'Iceland', region: 'Europe' },
  IND: { iso2: 'IN', iso3: 'IND', name: 'India', region: 'Asia' },
  IDN: { iso2: 'ID', iso3: 'IDN', name: 'Indonesia', region: 'Asia' },
  IRN: { iso2: 'IR', iso3: 'IRN', name: 'Iran', region: 'Middle East' },
  IRQ: { iso2: 'IQ', iso3: 'IRQ', name: 'Iraq', region: 'Middle East' },
  IRL: { iso2: 'IE', iso3: 'IRL', name: 'Ireland', region: 'Europe' },
  ISR: { iso2: 'IL', iso3: 'ISR', name: 'Israel', region: 'Middle East' },
  ITA: { iso2: 'IT', iso3: 'ITA', name: 'Italy', region: 'Europe' },
  JAM: { iso2: 'JM', iso3: 'JAM', name: 'Jamaica', region: 'Latin America' },
  JPN: { iso2: 'JP', iso3: 'JPN', name: 'Japan', region: 'Asia' },
  JOR: { iso2: 'JO', iso3: 'JOR', name: 'Jordan', region: 'Middle East' },
  KAZ: { iso2: 'KZ', iso3: 'KAZ', name: 'Kazakhstan', region: 'Asia' },
  KEN: { iso2: 'KE', iso3: 'KEN', name: 'Kenya', region: 'Africa' },
  KWT: { iso2: 'KW', iso3: 'KWT', name: 'Kuwait', region: 'Middle East' },
  KGZ: { iso2: 'KG', iso3: 'KGZ', name: 'Kyrgyzstan', region: 'Asia' },
  LAO: { iso2: 'LA', iso3: 'LAO', name: 'Laos', region: 'Asia' },
  LVA: { iso2: 'LV', iso3: 'LVA', name: 'Latvia', region: 'Europe' },
  LBN: { iso2: 'LB', iso3: 'LBN', name: 'Lebanon', region: 'Middle East' },
  LSO: { iso2: 'LS', iso3: 'LSO', name: 'Lesotho', region: 'Africa' },
  LBR: { iso2: 'LR', iso3: 'LBR', name: 'Liberia', region: 'Africa' },
  LBY: { iso2: 'LY', iso3: 'LBY', name: 'Libya', region: 'Africa' },
  LTU: { iso2: 'LT', iso3: 'LTU', name: 'Lithuania', region: 'Europe' },
  LUX: { iso2: 'LU', iso3: 'LUX', name: 'Luxembourg', region: 'Europe' },
  MDG: { iso2: 'MG', iso3: 'MDG', name: 'Madagascar', region: 'Africa' },
  MWI: { iso2: 'MW', iso3: 'MWI', name: 'Malawi', region: 'Africa' },
  MYS: { iso2: 'MY', iso3: 'MYS', name: 'Malaysia', region: 'Asia' },
  MLI: { iso2: 'ML', iso3: 'MLI', name: 'Mali', region: 'Africa' },
  MRT: { iso2: 'MR', iso3: 'MRT', name: 'Mauritania', region: 'Africa' },
  MUS: { iso2: 'MU', iso3: 'MUS', name: 'Mauritius', region: 'Africa' },
  MEX: { iso2: 'MX', iso3: 'MEX', name: 'Mexico', region: 'Latin America' },
  MDA: { iso2: 'MD', iso3: 'MDA', name: 'Moldova', region: 'Europe' },
  MNG: { iso2: 'MN', iso3: 'MNG', name: 'Mongolia', region: 'Asia' },
  MNE: { iso2: 'ME', iso3: 'MNE', name: 'Montenegro', region: 'Europe' },
  MAR: { iso2: 'MA', iso3: 'MAR', name: 'Morocco', region: 'Africa' },
  MOZ: { iso2: 'MZ', iso3: 'MOZ', name: 'Mozambique', region: 'Africa' },
  MMR: { iso2: 'MM', iso3: 'MMR', name: 'Myanmar', region: 'Asia' },
  NAM: { iso2: 'NA', iso3: 'NAM', name: 'Namibia', region: 'Africa' },
  NPL: { iso2: 'NP', iso3: 'NPL', name: 'Nepal', region: 'Asia' },
  NLD: { iso2: 'NL', iso3: 'NLD', name: 'Netherlands', region: 'Europe' },
  NZL: { iso2: 'NZ', iso3: 'NZL', name: 'New Zealand', region: 'Oceania' },
  NIC: { iso2: 'NI', iso3: 'NIC', name: 'Nicaragua', region: 'Latin America' },
  NER: { iso2: 'NE', iso3: 'NER', name: 'Niger', region: 'Africa' },
  NGA: { iso2: 'NG', iso3: 'NGA', name: 'Nigeria', region: 'Africa' },
  MKD: { iso2: 'MK', iso3: 'MKD', name: 'North Macedonia', region: 'Europe' },
  NOR: { iso2: 'NO', iso3: 'NOR', name: 'Norway', region: 'Europe' },
  OMN: { iso2: 'OM', iso3: 'OMN', name: 'Oman', region: 'Middle East' },
  PAK: { iso2: 'PK', iso3: 'PAK', name: 'Pakistan', region: 'Asia' },
  PAN: { iso2: 'PA', iso3: 'PAN', name: 'Panama', region: 'Latin America' },
  PNG: { iso2: 'PG', iso3: 'PNG', name: 'Papua New Guinea', region: 'Oceania' },
  PRY: { iso2: 'PY', iso3: 'PRY', name: 'Paraguay', region: 'Latin America' },
  PER: { iso2: 'PE', iso3: 'PER', name: 'Peru', region: 'Latin America' },
  PHL: { iso2: 'PH', iso3: 'PHL', name: 'Philippines', region: 'Asia' },
  POL: { iso2: 'PL', iso3: 'POL', name: 'Poland', region: 'Europe' },
  PRT: { iso2: 'PT', iso3: 'PRT', name: 'Portugal', region: 'Europe' },
  QAT: { iso2: 'QA', iso3: 'QAT', name: 'Qatar', region: 'Middle East' },
  ROU: { iso2: 'RO', iso3: 'ROU', name: 'Romania', region: 'Europe' },
  RUS: { iso2: 'RU', iso3: 'RUS', name: 'Russia', region: 'Europe' },
  RWA: { iso2: 'RW', iso3: 'RWA', name: 'Rwanda', region: 'Africa' },
  SAU: { iso2: 'SA', iso3: 'SAU', name: 'Saudi Arabia', region: 'Middle East' },
  SEN: { iso2: 'SN', iso3: 'SEN', name: 'Senegal', region: 'Africa' },
  SRB: { iso2: 'RS', iso3: 'SRB', name: 'Serbia', region: 'Europe' },
  SLE: { iso2: 'SL', iso3: 'SLE', name: 'Sierra Leone', region: 'Africa' },
  SGP: { iso2: 'SG', iso3: 'SGP', name: 'Singapore', region: 'Asia' },
  SVK: { iso2: 'SK', iso3: 'SVK', name: 'Slovakia', region: 'Europe' },
  SVN: { iso2: 'SI', iso3: 'SVN', name: 'Slovenia', region: 'Europe' },
  SOM: { iso2: 'SO', iso3: 'SOM', name: 'Somalia', region: 'Africa' },
  ZAF: { iso2: 'ZA', iso3: 'ZAF', name: 'South Africa', region: 'Africa' },
  KOR: { iso2: 'KR', iso3: 'KOR', name: 'South Korea', region: 'Asia' },
  SSD: { iso2: 'SS', iso3: 'SSD', name: 'South Sudan', region: 'Africa' },
  ESP: { iso2: 'ES', iso3: 'ESP', name: 'Spain', region: 'Europe' },
  LKA: { iso2: 'LK', iso3: 'LKA', name: 'Sri Lanka', region: 'Asia' },
  SDN: { iso2: 'SD', iso3: 'SDN', name: 'Sudan', region: 'Africa' },
  SUR: { iso2: 'SR', iso3: 'SUR', name: 'Suriname', region: 'Latin America' },
  SWE: { iso2: 'SE', iso3: 'SWE', name: 'Sweden', region: 'Europe' },
  CHE: { iso2: 'CH', iso3: 'CHE', name: 'Switzerland', region: 'Europe' },
  SYR: { iso2: 'SY', iso3: 'SYR', name: 'Syria', region: 'Middle East' },
  TWN: { iso2: 'TW', iso3: 'TWN', name: 'Taiwan', region: 'Asia' },
  TJK: { iso2: 'TJ', iso3: 'TJK', name: 'Tajikistan', region: 'Asia' },
  TZA: { iso2: 'TZ', iso3: 'TZA', name: 'Tanzania', region: 'Africa' },
  THA: { iso2: 'TH', iso3: 'THA', name: 'Thailand', region: 'Asia' },
  TLS: { iso2: 'TL', iso3: 'TLS', name: 'Timor-Leste', region: 'Asia' },
  TGO: { iso2: 'TG', iso3: 'TGO', name: 'Togo', region: 'Africa' },
  TTO: { iso2: 'TT', iso3: 'TTO', name: 'Trinidad and Tobago', region: 'Latin America' },
  TUN: { iso2: 'TN', iso3: 'TUN', name: 'Tunisia', region: 'Africa' },
  TUR: { iso2: 'TR', iso3: 'TUR', name: 'Turkey', region: 'Europe' },
  TKM: { iso2: 'TM', iso3: 'TKM', name: 'Turkmenistan', region: 'Asia' },
  UGA: { iso2: 'UG', iso3: 'UGA', name: 'Uganda', region: 'Africa' },
  UKR: { iso2: 'UA', iso3: 'UKR', name: 'Ukraine', region: 'Europe' },
  ARE: { iso2: 'AE', iso3: 'ARE', name: 'United Arab Emirates', region: 'Middle East' },
  GBR: { iso2: 'GB', iso3: 'GBR', name: 'United Kingdom', region: 'Europe' },
  USA: { iso2: 'US', iso3: 'USA', name: 'United States', region: 'North America' },
  URY: { iso2: 'UY', iso3: 'URY', name: 'Uruguay', region: 'Latin America' },
  UZB: { iso2: 'UZ', iso3: 'UZB', name: 'Uzbekistan', region: 'Asia' },
  VEN: { iso2: 'VE', iso3: 'VEN', name: 'Venezuela', region: 'Latin America' },
  VNM: { iso2: 'VN', iso3: 'VNM', name: 'Vietnam', region: 'Asia' },
  YEM: { iso2: 'YE', iso3: 'YEM', name: 'Yemen', region: 'Middle East' },
  ZMB: { iso2: 'ZM', iso3: 'ZMB', name: 'Zambia', region: 'Africa' },
  ZWE: { iso2: 'ZW', iso3: 'ZWE', name: 'Zimbabwe', region: 'Africa' },
};

// Reverse lookup: ISO2 → ISO3
export const ISO2_TO_ISO3: Record<string, string> = {};
for (const [iso3, meta] of Object.entries(ISO3_TO_COUNTRY)) {
  ISO2_TO_ISO3[meta.iso2] = iso3;
}

// World Bank uses ISO3 codes like "USA", Climate TRACE also uses "USA"
// World Bank response has countryiso3code field
